### ISSUE TITLE
Black Screen when using with DSPRE Reloaded 1.11.1

### ISSUE THREAD

**Issue by GaryGoesSky** [SpagoAsparago/DS-Starter-Editor#1]
I am starting the programme in virtual studio, the starter seleciton recognises the game (Heart Gold) and when I select the folder (rom_DSPRE_contents), it recognises which starters are selected and if alterations were made and saved. I have tried to change the starters to the Kanto trio. I apply the changes, close the Starter Editor, then open DSPRE and load the rom (rom.nds). I choose to look at the previously extracted files and save. If I say no, then I am asked to re-extract, which as far as I can tell, is what I want to avoid. I save the ROM in DSPRE without making any further alterations.

Everytime I load the game and go to starter selection, I am met with a black screen. This has occured with both fresh and DSPRE edited ROMs.

I have ensured it is a US ROM. I have made sure not to re-extract. I am not sure why I am getting a black screen,

**Comment by SpagoAsparago** [comment]
I tested it with a fresh HG ROM,  and the game works when changing the starters. 

Is there a reason that you're running the tool from visual studio instead of the executable from the releases?

**Comment by GaryGoesSky** [comment]
Hi! I realised I had not used the executable from the releases but just simply downloaded the project folder. It works perfectly! Thank you so much!

**Comment by SpagoAsparago** [comment]
Glad to hear it. I'll close the issue.
